image:
  service: "ghcr.io/youruser/ai-infer-service:latest"
  loadgen: "ghcr.io/youruser/ai-loadgen:latest"

service:
  replicas: 1
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60

loadgen:
  qps: 2
  concurrency: 2