apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-infer-service
spec:
  replicas: {{ .Values.service.replicas }}
  selector:
    matchLabels:
      app: ai-infer-service
  template:
    metadata:
      labels:
        app: ai-infer-service
    spec:
      containers:
        - name: service
          image: {{ .Values.image.service }}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
          resources:
            {{- toYaml .Values.service.resources | nindent 12 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-loadgen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-loadgen
  template:
    metadata:
      labels:
        app: ai-loadgen
    spec:
      containers:
        - name: loadgen
          image: {{ .Values.image.loadgen }}
          env:
            - name: SERVICE_URL
              value: "http://ai-infer-service:8080"
            - name: QPS
              value: "{{ .Values.loadgen.qps }}"
            - name: CONCURRENCY
              value: "{{ .Values.loadgen.concurrency }}"
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: ai-infer-service
spec:
  selector:
    app: ai-infer-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
