apiVersion: v1
kind: Service
metadata:
  name: ai-infer-service
  labels:
    app: ai-infer
spec:
  selector:
    app: ai-infer
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  type: ClusterIP
{{- if .Values.loadgen.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: ai-loadgen-metrics
  labels:
    app: ai-loadgen
spec:
  selector:
    app: ai-loadgen
  ports:
    - name: metrics
      port: 9090
      targetPort: metrics
  type: ClusterIP
{{- end }}
